// languagesOptions.js
const languagesOptions = [
    { value: 'tr', label: 'Türkçe' },
    { value: 'en', label: 'English' },
    { value: 'de', label: 'Almanca' },
    { value: 'fr', label: 'Fransızca' },
    { value: 'es', label: 'İspanyolca' },
    { value: 'ar', label: 'Arapça' },
    { value: 'ru', label: 'Rusça' },
    { value: 'zh', label: 'Çince' },
    { value: 'el', label: 'Yunanca' },
    { value: 'ja', label: 'Japonca' },
    { value: 'af', label: 'Afrikanca' },
    { value: 'az', label: 'Azerice' },
    { value: 'bn', label: 'Bengalce' },
    { value: 'bs', label: 'Boşnakça' },
    { value: 'ca', label: 'Katalanca' },
    { value: 'cs', label: 'Çekçe' },
    { value: 'da', label: 'Danca' },
    { value: 'hr', label: 'Hırvatça' },
    { value: 'hi', label: 'Hintçe' },
    { value: 'hu', label: 'Macarca' },
    { value: 'id', label: 'Endonezce' },
    { value: 'it', label: 'İtalyanca' },
    { value: 'ko', label: 'Korece' },
    { value: 'lt', label: 'Litvanca' },
    { value: 'lv', label: 'Letonca' },
    { value: 'mk', label: 'Makedonca' },
    { value: 'ml', label: 'Malayalamca' },
    { value: 'mn', label: 'Moğolca' },
    { value: 'mr', label: 'Marathi' },
    { value: 'mt', label: 'Maltaca' },
    { value: 'nl', label: 'Flemenkçe' },
    { value: 'no', label: 'Norveççe' },
    { value: 'pl', label: 'Lehçe' },
    { value: 'pt', label: 'Portekizce' },
    { value: 'ro', label: 'Romence' },
    { value: 'sk', label: 'Slovakça' },
    { value: 'sl', label: 'Slovence' },
    { value: 'sr', label: 'Sırpça' },
    { value: 'sv', label: 'İsveççe' },
    { value: 'sw', label: 'Svahili' },
    { value: 'th', label: 'Tayca' },
    { value: 'uk', label: 'Ukraynaca' },
    { value: 'vi', label: 'Vietnamca' },
    { value: 'be', label: 'Beyaz Rusça' },
    { value: 'cy', label: 'Galli' },
    { value: 'eo', label: 'Esperanto' },
    { value: 'et', label: 'Estonca' },
    { value: 'fi', label: 'Fince' },
    { value: 'gd', label: 'İskoç Galcesi' },
    { value: 'gl', label: 'Galician' },
    { value: 'gu', label: 'Gujarati' },
    { value: 'ha', label: 'Hausa' },
    { value: 'hy', label: 'Ermenice' },
    { value: 'is', label: 'İzlandaca' },
    { value: 'jv', label: 'Cava' },
    { value: 'ka', label: 'Gürcüce' },
    { value: 'km', label: 'Khmerce' },
    { value: 'ku', label: 'Kürtçe' },
    { value: 'la', label: 'Latince' },
    { value: 'lb', label: 'Lüksemburgca' },
    { value: 'mg', label: 'Malagazca' },
    { value: 'mi', label: 'Maori' },
    { value: 'my', label: 'Birmanca' },
    { value: 'pa', label: 'Punjabi' },
    { value: 'ps', label: 'Peştu' },
    { value: 'qu', label: 'Keçuva' },
    { value: 'sd', label: 'Sindhi' },
    { value: 'so', label: 'Somali' },
    { value: 'su', label: 'Sundanca' },
    { value: 'tt', label: 'Tatarca' },
    { value: 'xh', label: 'Xhosa' },
    { value: 'yi', label: 'Yidiş' },
    { value: 'zu', label: 'Zulu' }
];

export default languagesOptions;
